import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "black",
    },
    brand: {
      resizeMode: "contain",
      tintColor: 'white',
      height: 150,
      width: 150,
    },
    brand2: {
      resizeMode: "contain",
      tintColor: 'white',
      width: 85,
      height: 85,
    },
    label: {  // under profile ex: applicant name 
      fontSize: 12,
      marginBottom: 10,
      marginRight: 80,
      marginTop: 10,
      color: 'white',
      },
    titlemainContainer: {   // for the categories header under skills
      flex: 1,
      flexDirection: 'row',
      columnGap: 10,
      top: -25,
      marginHorizontal: 50,
      justifyContent: 'center',
      alignContent: 'center',
    },
    titleContainer: {
      flex: 1,
    },
    text: {   // text style for the list buttons of skills
      textTransform: 'uppercase',
      color: 'white',
      fontSize: 9,
      },
    text2: {   // text style for the list buttons of skills under design & creative
      textTransform: 'uppercase',
      color: 'white',
      fontSize: 12,
      },
    inputField: {
      width: '100%',
      height: 30, //adjust
      borderBottomColor: 'white',
      borderWidth: 1.5,
      backgroundColor: 'black',
      marginTop: -12,
      },
    centerInput: {  // SignupScreen page
      width: '65%',
      height: 70,
      borderColor: 'black',
      borderWidth: 1.5,
      marginBottom: 4,
      paddingHorizontal: 10,
      alignSelf: 'center',
      bordeColor: 'white',
    },
    normalText: {
      fontSize: 10,
      fontWeight: '100',
      marginBottom: 10,
      textAlign: 'left',
      justifyContent: 'left',
      alignSelf: 'center',
      marginTop: 10,
      color: 'white',
      },
    activeLink: {
      fontSize: 10,
      fontWeight: 'bold',
      marginBottom: 10,
      textAlign: 'right',
      justifyContent: 'right',
      marginTop: 10,
    },
    header: {   //step 1 profile and skills & step 2 files and portfolio
      fontSize: 18,
      color: "#fff",
      textTransform: "uppercase",
      fontWeight: '400',
      paddingTop: 20,
      columnGap: "2rem",
      fontWeight: 'bold',
    },
    subProfile: { //under profile
      fontSize: 10,
      textTransform: "uppercase",
      marginHorizontal: 50,
      top: -20,
    },
    subHeader2: {
      fontSize: 10,
      color: 'gray',
      fontWeight: "bold",
      paddingTop: 20,
      columnGap: "2rem",
      marginTop: ".5rem",
    },
    buttonTitle: {
      textTransform: 'uppercase',
    },
    lineContainer: {  // for profile
      position: 'relevant',
      top: -26,
      left: 1,
      marginRight: 30,
      borderColor: 'white',
    },
    lineContainer2: { // for skills
      position: 'relevant',
      top: -61,
      left: 33,
      marginRight: 375,
      borderColor: 'white',
    },
    line: {
      height: 5,
      backgroundColor: 'white',
    },
});
export const buttonContainer = StyleSheet.create({
    container: {
      flex: 1, 
      alignItems: 'stretch', 
      justifyContent: 'center', 
      padding: 65, 
      marginTop: -70,
    },
    buttonContainer: { //step 1 and step 2 buttons
      flexDirection: 'row',
      columnGap: 50,
      borderRadius: 50,
    },
    buttonLabels: { // for step 1 and step 2
      borderRadius: 150,
      fontWeight: 50,
    },
    skillssubContainer: { //  for the skills list under design & creative
      marginHorizontal: 55,
      flexDirection: 'row', 
      flexWrap: 'wrap', 
      top: -60,
    },
    skillsList: {   // for the list under design & creative
      backgroundColor: '#444', 
      borderRadius: 60,
      marginHorizontal: 5,
      marginVertical: 5,
      paddingVertical: 2,
      paddingHorizontal: 10,
      justifyContent: 'center',
    },
    proceedContainer: { 
      right: -140,
      top: 10,
      backgroundColor: '#fff',
      flexDirection: 'row',
    },
    proceedButton: {
      backgroundColor: '#444',
      paddingHorizontal: 20,
      paddingVertical: 10,
    },
    proceedButtonText: {
      textTransform: 'uppercase',
      color: 'white',
      fontSize: 15,
    }
  });
  export const logoContainer = StyleSheet.create({ //step 1 registration logos
    container: {
      justifyContent: 'center', 
      alignItems: 'center', 
    },
    subContainer: { //for step 1 registration logos
      width: "258px",
      height: "150px",
      flexDirection: 'row',
      columnGap: 10,
      justifyContent: 'center', 
      alignItems: 'center', 
      backgroundColor: 'black',
    },
    miniContainer: {  //for step 1 header
      alignSelf: 'flex-start',
      marginLeft: 30,
      marginBottom: 18,
    },
    miniContainer2: {    //for the personal information
      flexDirection:'column',
      height: 280,
    },
    skillsContainer: {   //for header2
      flexDirection:'row',
      marginLeft: 30,
      borderWidth: 2,
      top: -30,
      columnGap: 5,
      paddingTop: 2,
      paddingVertical: 2,
    }
  });
  export const subFile = StyleSheet.create({  // for signup2
    container: {
    marginHorizontal: 30,
    paddingHorizontal: 20,
  },
    resumeContainer: { // container for the resume label under Files
      height: 20,
      top: -2.5,
      marginHorizontal: 50,
  },
  text: { // font style for resume label and upload label
      fontSize: 12,
      textTransform: "uppercase",
      color: 'white',
      fontWeight: '600',
  },
  uploadContainer: {  // upload label under Portfolio
    height: 20,
    top: 10,
    marginHorizontal: 50,
},
  choosefileContainer2: {  
    borderWidth: 2, 
    borderColor: '#444',
    height: 25,
    top: 19,
    marginHorizontal: 50,
    flexDirection: 'row',
    columnGap: 20,
    borderTopWidth: 0,
    borderLeftWidth: 0,
    borderRightWidth: 0,
  },
  choosefileContainer: {  // under resume 
    borderWidth: 2, 
    borderColor: '#444',
    height: 25,
    top: 8,
    marginHorizontal: 50,
    flexDirection: 'row',
    columnGap: 20,
    borderTopWidth: 0,
    borderLeftWidth: 0,
    borderRightWidth: 0,
  },
  fileInputButton: {
    padding: 10,
    backgroundColor: '#444',
    alignItems: 'center',
    justifyContent: 'center',
    top: 1,
    borderColor: 'white',
    borderColor: 'white',
  },
  fileNamePlaceholder: {
    marginTop: 3,
  },
  buttonStyle: {  // for "choose file"
    fontSize: 15,
    fontWeight: '300',
    color: 'white',
  },
    text: { // label like resume and upload // maybe delete this later?
    fontSize: 12,
    marginRight: 80,
    marginTop: 10,
    color: 'white',
    alignSelf: 'flex-start',
    textTransform: 'uppercase',
    },
    imageContainer: {
    marginHorizontal: 30,
    paddingHorizontal: 20,
    top: 50,
    height: 'auto',
    width: '85%',
    flexDirection: 'row',
    columnGap: 20,
    },
    previewText: {
    fontSize: 15,
    marginRight: 80,
    top: 30,
    left: 51,
    color: 'white',
    textTransform: 'uppercase',
    },
    image: {
      height: 100,
      width: '45%',
    },
    lineContainer: {    // for line design for files
      position: 'relevant',
        left: 30,
        marginRight: 370,
        top: 21,
    },
    lineContainer3: {   // for portfolio line design
      position: 'relevant',
      left: 30,
      marginRight: 370,
      top: 35,
    },
    line2: {  // for line designs for files and portfolio (headers)
        height: 5,
        backgroundColor: 'white',
    },
    lineContainer2: {  // lines for below portfolio section
      flexDirection: 'row',
      top: 75,
      marginHorizontal: 50,
      columnGap: 40,
      alignItems: 'center',
    },  
    line: { // lines under portfolio
      flex: 1,
      height: 1,
      backgroundColor: 'white',
    },
    orLine: { // // lines under portfolio
      fontSize: 12,
      textTransform: 'uppercase',
      color: 'white',
    },
    insertContainer: {
    marginHorizontal: 30,
    paddingHorizontal: 20,
    top: 90,
    rowGap: 10,
    },
    submitButton: {
      position: 'absolute',
      right: 40,
      marginBottom: 50,
      top: 800,
      backgroundColor: '#fff',
    },
    backContainer: {
      position: 'absolute',
      bottom: -227, 
      alignSelf: 'center', 
      left: 125,
      backgroundColor: 'black',
    },
    backButton: {
     fontSize: 12,
    color: 'white',
    textTransform: 'uppercase',
    fontWeight: "bold",
    },
    portfolioContainer: { // portfolio header
      alignSelf: 'flex-start',
      marginLeft: 30,
      marginBottom: 18,
      top: 17,
    }
  })
